package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WpBpMessagesMessages generated by hbm2java
 */
public class WpBpMessagesMessages  implements java.io.Serializable {


     private Long id;
     private long threadId;
     private long senderId;
     private String subject;
     private String message;
     private Date dateSent;

    public WpBpMessagesMessages() {
    }

    public WpBpMessagesMessages(long threadId, long senderId, String subject, String message, Date dateSent) {
       this.threadId = threadId;
       this.senderId = senderId;
       this.subject = subject;
       this.message = message;
       this.dateSent = dateSent;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getThreadId() {
        return this.threadId;
    }
    
    public void setThreadId(long threadId) {
        this.threadId = threadId;
    }
    public long getSenderId() {
        return this.senderId;
    }
    
    public void setSenderId(long senderId) {
        this.senderId = senderId;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getDateSent() {
        return this.dateSent;
    }
    
    public void setDateSent(Date dateSent) {
        this.dateSent = dateSent;
    }




}


