package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpBpXprofileGroups generated by hbm2java
 */
public class WpBpXprofileGroups  implements java.io.Serializable {


     private Long id;
     private String name;
     private String description;
     private long groupOrder;
     private boolean canDelete;

    public WpBpXprofileGroups() {
    }

    public WpBpXprofileGroups(String name, String description, long groupOrder, boolean canDelete) {
       this.name = name;
       this.description = description;
       this.groupOrder = groupOrder;
       this.canDelete = canDelete;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public long getGroupOrder() {
        return this.groupOrder;
    }
    
    public void setGroupOrder(long groupOrder) {
        this.groupOrder = groupOrder;
    }
    public boolean isCanDelete() {
        return this.canDelete;
    }
    
    public void setCanDelete(boolean canDelete) {
        this.canDelete = canDelete;
    }




}


