package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpBpMessagesMeta generated by hbm2java
 */
public class WpBpMessagesMeta  implements java.io.Serializable {


     private Long id;
     private long messageId;
     private String metaKey;
     private String metaValue;

    public WpBpMessagesMeta() {
    }

	
    public WpBpMessagesMeta(long messageId) {
        this.messageId = messageId;
    }
    public WpBpMessagesMeta(long messageId, String metaKey, String metaValue) {
       this.messageId = messageId;
       this.metaKey = metaKey;
       this.metaValue = metaValue;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(long messageId) {
        this.messageId = messageId;
    }
    public String getMetaKey() {
        return this.metaKey;
    }
    
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey;
    }
    public String getMetaValue() {
        return this.metaValue;
    }
    
    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue;
    }




}


