package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpBpXprofileFields generated by hbm2java
 */
public class WpBpXprofileFields  implements java.io.Serializable {


     private Long id;
     private long groupId;
     private long parentId;
     private String type;
     private String name;
     private String description;
     private boolean isRequired;
     private boolean isDefaultOption;
     private long fieldOrder;
     private long optionOrder;
     private String orderBy;
     private boolean canDelete;

    public WpBpXprofileFields() {
    }

    public WpBpXprofileFields(long groupId, long parentId, String type, String name, String description, boolean isRequired, boolean isDefaultOption, long fieldOrder, long optionOrder, String orderBy, boolean canDelete) {
       this.groupId = groupId;
       this.parentId = parentId;
       this.type = type;
       this.name = name;
       this.description = description;
       this.isRequired = isRequired;
       this.isDefaultOption = isDefaultOption;
       this.fieldOrder = fieldOrder;
       this.optionOrder = optionOrder;
       this.orderBy = orderBy;
       this.canDelete = canDelete;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }
    public long getParentId() {
        return this.parentId;
    }
    
    public void setParentId(long parentId) {
        this.parentId = parentId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isIsRequired() {
        return this.isRequired;
    }
    
    public void setIsRequired(boolean isRequired) {
        this.isRequired = isRequired;
    }
    public boolean isIsDefaultOption() {
        return this.isDefaultOption;
    }
    
    public void setIsDefaultOption(boolean isDefaultOption) {
        this.isDefaultOption = isDefaultOption;
    }
    public long getFieldOrder() {
        return this.fieldOrder;
    }
    
    public void setFieldOrder(long fieldOrder) {
        this.fieldOrder = fieldOrder;
    }
    public long getOptionOrder() {
        return this.optionOrder;
    }
    
    public void setOptionOrder(long optionOrder) {
        this.optionOrder = optionOrder;
    }
    public String getOrderBy() {
        return this.orderBy;
    }
    
    public void setOrderBy(String orderBy) {
        this.orderBy = orderBy;
    }
    public boolean isCanDelete() {
        return this.canDelete;
    }
    
    public void setCanDelete(boolean canDelete) {
        this.canDelete = canDelete;
    }




}


