package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WpBpXprofileData generated by hbm2java
 */
public class WpBpXprofileData  implements java.io.Serializable {


     private Long id;
     private long fieldId;
     private long userId;
     private String value;
     private Date lastUpdated;

    public WpBpXprofileData() {
    }

    public WpBpXprofileData(long fieldId, long userId, String value, Date lastUpdated) {
       this.fieldId = fieldId;
       this.userId = userId;
       this.value = value;
       this.lastUpdated = lastUpdated;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getFieldId() {
        return this.fieldId;
    }
    
    public void setFieldId(long fieldId) {
        this.fieldId = fieldId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


