package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpBpXprofileMeta generated by hbm2java
 */
public class WpBpXprofileMeta  implements java.io.Serializable {


     private Long id;
     private long objectId;
     private String objectType;
     private String metaKey;
     private String metaValue;

    public WpBpXprofileMeta() {
    }

	
    public WpBpXprofileMeta(long objectId, String objectType) {
        this.objectId = objectId;
        this.objectType = objectType;
    }
    public WpBpXprofileMeta(long objectId, String objectType, String metaKey, String metaValue) {
       this.objectId = objectId;
       this.objectType = objectType;
       this.metaKey = metaKey;
       this.metaValue = metaValue;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(long objectId) {
        this.objectId = objectId;
    }
    public String getObjectType() {
        return this.objectType;
    }
    
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }
    public String getMetaKey() {
        return this.metaKey;
    }
    
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey;
    }
    public String getMetaValue() {
        return this.metaValue;
    }
    
    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue;
    }




}


