package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WpBpActivity generated by hbm2java
 */
public class WpBpActivity  implements java.io.Serializable {


     private Long id;
     private long userId;
     private String component;
     private String type;
     private String action;
     private String content;
     private String primaryLink;
     private long itemId;
     private Long secondaryItemId;
     private Date dateRecorded;
     private Boolean hideSitewide;
     private int mpttLeft;
     private int mpttRight;
     private boolean isSpam;

    public WpBpActivity() {
    }

	
    public WpBpActivity(long userId, String component, String type, String action, String content, String primaryLink, long itemId, Date dateRecorded, int mpttLeft, int mpttRight, boolean isSpam) {
        this.userId = userId;
        this.component = component;
        this.type = type;
        this.action = action;
        this.content = content;
        this.primaryLink = primaryLink;
        this.itemId = itemId;
        this.dateRecorded = dateRecorded;
        this.mpttLeft = mpttLeft;
        this.mpttRight = mpttRight;
        this.isSpam = isSpam;
    }
    public WpBpActivity(long userId, String component, String type, String action, String content, String primaryLink, long itemId, Long secondaryItemId, Date dateRecorded, Boolean hideSitewide, int mpttLeft, int mpttRight, boolean isSpam) {
       this.userId = userId;
       this.component = component;
       this.type = type;
       this.action = action;
       this.content = content;
       this.primaryLink = primaryLink;
       this.itemId = itemId;
       this.secondaryItemId = secondaryItemId;
       this.dateRecorded = dateRecorded;
       this.hideSitewide = hideSitewide;
       this.mpttLeft = mpttLeft;
       this.mpttRight = mpttRight;
       this.isSpam = isSpam;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getComponent() {
        return this.component;
    }
    
    public void setComponent(String component) {
        this.component = component;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getPrimaryLink() {
        return this.primaryLink;
    }
    
    public void setPrimaryLink(String primaryLink) {
        this.primaryLink = primaryLink;
    }
    public long getItemId() {
        return this.itemId;
    }
    
    public void setItemId(long itemId) {
        this.itemId = itemId;
    }
    public Long getSecondaryItemId() {
        return this.secondaryItemId;
    }
    
    public void setSecondaryItemId(Long secondaryItemId) {
        this.secondaryItemId = secondaryItemId;
    }
    public Date getDateRecorded() {
        return this.dateRecorded;
    }
    
    public void setDateRecorded(Date dateRecorded) {
        this.dateRecorded = dateRecorded;
    }
    public Boolean getHideSitewide() {
        return this.hideSitewide;
    }
    
    public void setHideSitewide(Boolean hideSitewide) {
        this.hideSitewide = hideSitewide;
    }
    public int getMpttLeft() {
        return this.mpttLeft;
    }
    
    public void setMpttLeft(int mpttLeft) {
        this.mpttLeft = mpttLeft;
    }
    public int getMpttRight() {
        return this.mpttRight;
    }
    
    public void setMpttRight(int mpttRight) {
        this.mpttRight = mpttRight;
    }
    public boolean isIsSpam() {
        return this.isSpam;
    }
    
    public void setIsSpam(boolean isSpam) {
        this.isSpam = isSpam;
    }




}


