package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpCommentmeta generated by hbm2java
 */
public class WpCommentmeta  implements java.io.Serializable {


     private Long metaId;
     private long commentId;
     private String metaKey;
     private String metaValue;

    public WpCommentmeta() {
    }

	
    public WpCommentmeta(long commentId) {
        this.commentId = commentId;
    }
    public WpCommentmeta(long commentId, String metaKey, String metaValue) {
       this.commentId = commentId;
       this.metaKey = metaKey;
       this.metaValue = metaValue;
    }
   
    public Long getMetaId() {
        return this.metaId;
    }
    
    public void setMetaId(Long metaId) {
        this.metaId = metaId;
    }
    public long getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(long commentId) {
        this.commentId = commentId;
    }
    public String getMetaKey() {
        return this.metaKey;
    }
    
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey;
    }
    public String getMetaValue() {
        return this.metaValue;
    }
    
    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue;
    }




}


