package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WpComments generated by hbm2java
 */
public class WpComments  implements java.io.Serializable {


     private Long commentId;
     private long commentPostId;
     private String commentAuthor;
     private String commentAuthorEmail;
     private String commentAuthorUrl;
     private String commentAuthorIp;
     private Date commentDate;
     private Date commentDateGmt;
     private String commentContent;
     private int commentKarma;
     private String commentApproved;
     private String commentAgent;
     private String commentType;
     private long commentParent;
     private long userId;

    public WpComments() {
    }

    public WpComments(long commentPostId, String commentAuthor, String commentAuthorEmail, String commentAuthorUrl, String commentAuthorIp, Date commentDate, Date commentDateGmt, String commentContent, int commentKarma, String commentApproved, String commentAgent, String commentType, long commentParent, long userId) {
       this.commentPostId = commentPostId;
       this.commentAuthor = commentAuthor;
       this.commentAuthorEmail = commentAuthorEmail;
       this.commentAuthorUrl = commentAuthorUrl;
       this.commentAuthorIp = commentAuthorIp;
       this.commentDate = commentDate;
       this.commentDateGmt = commentDateGmt;
       this.commentContent = commentContent;
       this.commentKarma = commentKarma;
       this.commentApproved = commentApproved;
       this.commentAgent = commentAgent;
       this.commentType = commentType;
       this.commentParent = commentParent;
       this.userId = userId;
    }
   
    public Long getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }
    public long getCommentPostId() {
        return this.commentPostId;
    }
    
    public void setCommentPostId(long commentPostId) {
        this.commentPostId = commentPostId;
    }
    public String getCommentAuthor() {
        return this.commentAuthor;
    }
    
    public void setCommentAuthor(String commentAuthor) {
        this.commentAuthor = commentAuthor;
    }
    public String getCommentAuthorEmail() {
        return this.commentAuthorEmail;
    }
    
    public void setCommentAuthorEmail(String commentAuthorEmail) {
        this.commentAuthorEmail = commentAuthorEmail;
    }
    public String getCommentAuthorUrl() {
        return this.commentAuthorUrl;
    }
    
    public void setCommentAuthorUrl(String commentAuthorUrl) {
        this.commentAuthorUrl = commentAuthorUrl;
    }
    public String getCommentAuthorIp() {
        return this.commentAuthorIp;
    }
    
    public void setCommentAuthorIp(String commentAuthorIp) {
        this.commentAuthorIp = commentAuthorIp;
    }
    public Date getCommentDate() {
        return this.commentDate;
    }
    
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }
    public Date getCommentDateGmt() {
        return this.commentDateGmt;
    }
    
    public void setCommentDateGmt(Date commentDateGmt) {
        this.commentDateGmt = commentDateGmt;
    }
    public String getCommentContent() {
        return this.commentContent;
    }
    
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }
    public int getCommentKarma() {
        return this.commentKarma;
    }
    
    public void setCommentKarma(int commentKarma) {
        this.commentKarma = commentKarma;
    }
    public String getCommentApproved() {
        return this.commentApproved;
    }
    
    public void setCommentApproved(String commentApproved) {
        this.commentApproved = commentApproved;
    }
    public String getCommentAgent() {
        return this.commentAgent;
    }
    
    public void setCommentAgent(String commentAgent) {
        this.commentAgent = commentAgent;
    }
    public String getCommentType() {
        return this.commentType;
    }
    
    public void setCommentType(String commentType) {
        this.commentType = commentType;
    }
    public long getCommentParent() {
        return this.commentParent;
    }
    
    public void setCommentParent(long commentParent) {
        this.commentParent = commentParent;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }




}


