package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * WpEspRegistrationPayment generated by hbm2java
 */
public class WpEspRegistrationPayment  implements java.io.Serializable {


     private Integer rpyId;
     private int regId;
     private Integer payId;
     private BigDecimal rpyAmount;

    public WpEspRegistrationPayment() {
    }

	
    public WpEspRegistrationPayment(int regId, BigDecimal rpyAmount) {
        this.regId = regId;
        this.rpyAmount = rpyAmount;
    }
    public WpEspRegistrationPayment(int regId, Integer payId, BigDecimal rpyAmount) {
       this.regId = regId;
       this.payId = payId;
       this.rpyAmount = rpyAmount;
    }
   
    public Integer getRpyId() {
        return this.rpyId;
    }
    
    public void setRpyId(Integer rpyId) {
        this.rpyId = rpyId;
    }
    public int getRegId() {
        return this.regId;
    }
    
    public void setRegId(int regId) {
        this.regId = regId;
    }
    public Integer getPayId() {
        return this.payId;
    }
    
    public void setPayId(Integer payId) {
        this.payId = payId;
    }
    public BigDecimal getRpyAmount() {
        return this.rpyAmount;
    }
    
    public void setRpyAmount(BigDecimal rpyAmount) {
        this.rpyAmount = rpyAmount;
    }




}


