package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspEventQuestionGroup generated by hbm2java
 */
public class WpEspEventQuestionGroup  implements java.io.Serializable {


     private Integer eqgId;
     private long evtId;
     private int qsgId;
     private boolean eqgPrimary;

    public WpEspEventQuestionGroup() {
    }

    public WpEspEventQuestionGroup(long evtId, int qsgId, boolean eqgPrimary) {
       this.evtId = evtId;
       this.qsgId = qsgId;
       this.eqgPrimary = eqgPrimary;
    }
   
    public Integer getEqgId() {
        return this.eqgId;
    }
    
    public void setEqgId(Integer eqgId) {
        this.eqgId = eqgId;
    }
    public long getEvtId() {
        return this.evtId;
    }
    
    public void setEvtId(long evtId) {
        this.evtId = evtId;
    }
    public int getQsgId() {
        return this.qsgId;
    }
    
    public void setQsgId(int qsgId) {
        this.qsgId = qsgId;
    }
    public boolean isEqgPrimary() {
        return this.eqgPrimary;
    }
    
    public void setEqgPrimary(boolean eqgPrimary) {
        this.eqgPrimary = eqgPrimary;
    }




}


