package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WpEspLog generated by hbm2java
 */
public class WpEspLog  implements java.io.Serializable {


     private Integer logId;
     private Date logTime;
     private String objId;
     private String objType;
     private String logType;
     private String logMessage;
     private Integer logWpUser;

    public WpEspLog() {
    }

    public WpEspLog(Date logTime, String objId, String objType, String logType, String logMessage, Integer logWpUser) {
       this.logTime = logTime;
       this.objId = objId;
       this.objType = objType;
       this.logType = logType;
       this.logMessage = logMessage;
       this.logWpUser = logWpUser;
    }
   
    public Integer getLogId() {
        return this.logId;
    }
    
    public void setLogId(Integer logId) {
        this.logId = logId;
    }
    public Date getLogTime() {
        return this.logTime;
    }
    
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }
    public String getObjId() {
        return this.objId;
    }
    
    public void setObjId(String objId) {
        this.objId = objId;
    }
    public String getObjType() {
        return this.objType;
    }
    
    public void setObjType(String objType) {
        this.objType = objType;
    }
    public String getLogType() {
        return this.logType;
    }
    
    public void setLogType(String logType) {
        this.logType = logType;
    }
    public String getLogMessage() {
        return this.logMessage;
    }
    
    public void setLogMessage(String logMessage) {
        this.logMessage = logMessage;
    }
    public Integer getLogWpUser() {
        return this.logWpUser;
    }
    
    public void setLogWpUser(Integer logWpUser) {
        this.logWpUser = logWpUser;
    }




}


