package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspEventMessageTemplate generated by hbm2java
 */
public class WpEspEventMessageTemplate  implements java.io.Serializable {


     private Long emtId;
     private long evtId;
     private int grpId;

    public WpEspEventMessageTemplate() {
    }

    public WpEspEventMessageTemplate(long evtId, int grpId) {
       this.evtId = evtId;
       this.grpId = grpId;
    }
   
    public Long getEmtId() {
        return this.emtId;
    }
    
    public void setEmtId(Long emtId) {
        this.emtId = emtId;
    }
    public long getEvtId() {
        return this.evtId;
    }
    
    public void setEvtId(long evtId) {
        this.evtId = evtId;
    }
    public int getGrpId() {
        return this.grpId;
    }
    
    public void setGrpId(int grpId) {
        this.grpId = grpId;
    }




}


