package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspEventVenue generated by hbm2java
 */
public class WpEspEventVenue  implements java.io.Serializable {


     private Integer evvId;
     private long evtId;
     private long vnuId;
     private boolean evvPrimary;

    public WpEspEventVenue() {
    }

    public WpEspEventVenue(long evtId, long vnuId, boolean evvPrimary) {
       this.evtId = evtId;
       this.vnuId = vnuId;
       this.evvPrimary = evvPrimary;
    }
   
    public Integer getEvvId() {
        return this.evvId;
    }
    
    public void setEvvId(Integer evvId) {
        this.evvId = evvId;
    }
    public long getEvtId() {
        return this.evtId;
    }
    
    public void setEvtId(long evtId) {
        this.evtId = evtId;
    }
    public long getVnuId() {
        return this.vnuId;
    }
    
    public void setVnuId(long vnuId) {
        this.vnuId = vnuId;
    }
    public boolean isEvvPrimary() {
        return this.evvPrimary;
    }
    
    public void setEvvPrimary(boolean evvPrimary) {
        this.evvPrimary = evvPrimary;
    }




}


