package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspTicketPrice generated by hbm2java
 */
public class WpEspTicketPrice  implements java.io.Serializable {


     private Integer tkpId;
     private int tktId;
     private int prcId;

    public WpEspTicketPrice() {
    }

    public WpEspTicketPrice(int tktId, int prcId) {
       this.tktId = tktId;
       this.prcId = prcId;
    }
   
    public Integer getTkpId() {
        return this.tkpId;
    }
    
    public void setTkpId(Integer tkpId) {
        this.tkpId = tkpId;
    }
    public int getTktId() {
        return this.tktId;
    }
    
    public void setTktId(int tktId) {
        this.tktId = tktId;
    }
    public int getPrcId() {
        return this.prcId;
    }
    
    public void setPrcId(int prcId) {
        this.prcId = prcId;
    }




}


