package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspPaymentMethod generated by hbm2java
 */
public class WpEspPaymentMethod  implements java.io.Serializable {


     private Integer pmdId;
     private String pmdType;
     private String pmdName;
     private String pmdDesc;
     private String pmdAdminName;
     private String pmdAdminDesc;
     private String pmdSlug;
     private Integer pmdOrder;
     private boolean pmdDebugMode;
     private int pmdWpUser;
     private boolean pmdOpenByDefault;
     private String pmdButtonUrl;
     private String pmdScope;

    public WpEspPaymentMethod() {
    }

	
    public WpEspPaymentMethod(boolean pmdDebugMode, int pmdWpUser, boolean pmdOpenByDefault) {
        this.pmdDebugMode = pmdDebugMode;
        this.pmdWpUser = pmdWpUser;
        this.pmdOpenByDefault = pmdOpenByDefault;
    }
    public WpEspPaymentMethod(String pmdType, String pmdName, String pmdDesc, String pmdAdminName, String pmdAdminDesc, String pmdSlug, Integer pmdOrder, boolean pmdDebugMode, int pmdWpUser, boolean pmdOpenByDefault, String pmdButtonUrl, String pmdScope) {
       this.pmdType = pmdType;
       this.pmdName = pmdName;
       this.pmdDesc = pmdDesc;
       this.pmdAdminName = pmdAdminName;
       this.pmdAdminDesc = pmdAdminDesc;
       this.pmdSlug = pmdSlug;
       this.pmdOrder = pmdOrder;
       this.pmdDebugMode = pmdDebugMode;
       this.pmdWpUser = pmdWpUser;
       this.pmdOpenByDefault = pmdOpenByDefault;
       this.pmdButtonUrl = pmdButtonUrl;
       this.pmdScope = pmdScope;
    }
   
    public Integer getPmdId() {
        return this.pmdId;
    }
    
    public void setPmdId(Integer pmdId) {
        this.pmdId = pmdId;
    }
    public String getPmdType() {
        return this.pmdType;
    }
    
    public void setPmdType(String pmdType) {
        this.pmdType = pmdType;
    }
    public String getPmdName() {
        return this.pmdName;
    }
    
    public void setPmdName(String pmdName) {
        this.pmdName = pmdName;
    }
    public String getPmdDesc() {
        return this.pmdDesc;
    }
    
    public void setPmdDesc(String pmdDesc) {
        this.pmdDesc = pmdDesc;
    }
    public String getPmdAdminName() {
        return this.pmdAdminName;
    }
    
    public void setPmdAdminName(String pmdAdminName) {
        this.pmdAdminName = pmdAdminName;
    }
    public String getPmdAdminDesc() {
        return this.pmdAdminDesc;
    }
    
    public void setPmdAdminDesc(String pmdAdminDesc) {
        this.pmdAdminDesc = pmdAdminDesc;
    }
    public String getPmdSlug() {
        return this.pmdSlug;
    }
    
    public void setPmdSlug(String pmdSlug) {
        this.pmdSlug = pmdSlug;
    }
    public Integer getPmdOrder() {
        return this.pmdOrder;
    }
    
    public void setPmdOrder(Integer pmdOrder) {
        this.pmdOrder = pmdOrder;
    }
    public boolean isPmdDebugMode() {
        return this.pmdDebugMode;
    }
    
    public void setPmdDebugMode(boolean pmdDebugMode) {
        this.pmdDebugMode = pmdDebugMode;
    }
    public int getPmdWpUser() {
        return this.pmdWpUser;
    }
    
    public void setPmdWpUser(int pmdWpUser) {
        this.pmdWpUser = pmdWpUser;
    }
    public boolean isPmdOpenByDefault() {
        return this.pmdOpenByDefault;
    }
    
    public void setPmdOpenByDefault(boolean pmdOpenByDefault) {
        this.pmdOpenByDefault = pmdOpenByDefault;
    }
    public String getPmdButtonUrl() {
        return this.pmdButtonUrl;
    }
    
    public void setPmdButtonUrl(String pmdButtonUrl) {
        this.pmdButtonUrl = pmdButtonUrl;
    }
    public String getPmdScope() {
        return this.pmdScope;
    }
    
    public void setPmdScope(String pmdScope) {
        this.pmdScope = pmdScope;
    }




}


