package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspQuestion generated by hbm2java
 */
public class WpEspQuestion  implements java.io.Serializable {


     private Integer qstId;
     private String qstDisplayText;
     private String qstAdminLabel;
     private String qstSystem;
     private String qstType;
     private boolean qstRequired;
     private String qstRequiredText;
     private byte qstOrder;
     private boolean qstAdminOnly;
     private short qstMax;
     private Long qstWpUser;
     private byte qstDeleted;

    public WpEspQuestion() {
    }

	
    public WpEspQuestion(String qstDisplayText, String qstAdminLabel, String qstSystem, String qstType, boolean qstRequired, byte qstOrder, boolean qstAdminOnly, short qstMax, byte qstDeleted) {
        this.qstDisplayText = qstDisplayText;
        this.qstAdminLabel = qstAdminLabel;
        this.qstSystem = qstSystem;
        this.qstType = qstType;
        this.qstRequired = qstRequired;
        this.qstOrder = qstOrder;
        this.qstAdminOnly = qstAdminOnly;
        this.qstMax = qstMax;
        this.qstDeleted = qstDeleted;
    }
    public WpEspQuestion(String qstDisplayText, String qstAdminLabel, String qstSystem, String qstType, boolean qstRequired, String qstRequiredText, byte qstOrder, boolean qstAdminOnly, short qstMax, Long qstWpUser, byte qstDeleted) {
       this.qstDisplayText = qstDisplayText;
       this.qstAdminLabel = qstAdminLabel;
       this.qstSystem = qstSystem;
       this.qstType = qstType;
       this.qstRequired = qstRequired;
       this.qstRequiredText = qstRequiredText;
       this.qstOrder = qstOrder;
       this.qstAdminOnly = qstAdminOnly;
       this.qstMax = qstMax;
       this.qstWpUser = qstWpUser;
       this.qstDeleted = qstDeleted;
    }
   
    public Integer getQstId() {
        return this.qstId;
    }
    
    public void setQstId(Integer qstId) {
        this.qstId = qstId;
    }
    public String getQstDisplayText() {
        return this.qstDisplayText;
    }
    
    public void setQstDisplayText(String qstDisplayText) {
        this.qstDisplayText = qstDisplayText;
    }
    public String getQstAdminLabel() {
        return this.qstAdminLabel;
    }
    
    public void setQstAdminLabel(String qstAdminLabel) {
        this.qstAdminLabel = qstAdminLabel;
    }
    public String getQstSystem() {
        return this.qstSystem;
    }
    
    public void setQstSystem(String qstSystem) {
        this.qstSystem = qstSystem;
    }
    public String getQstType() {
        return this.qstType;
    }
    
    public void setQstType(String qstType) {
        this.qstType = qstType;
    }
    public boolean isQstRequired() {
        return this.qstRequired;
    }
    
    public void setQstRequired(boolean qstRequired) {
        this.qstRequired = qstRequired;
    }
    public String getQstRequiredText() {
        return this.qstRequiredText;
    }
    
    public void setQstRequiredText(String qstRequiredText) {
        this.qstRequiredText = qstRequiredText;
    }
    public byte getQstOrder() {
        return this.qstOrder;
    }
    
    public void setQstOrder(byte qstOrder) {
        this.qstOrder = qstOrder;
    }
    public boolean isQstAdminOnly() {
        return this.qstAdminOnly;
    }
    
    public void setQstAdminOnly(boolean qstAdminOnly) {
        this.qstAdminOnly = qstAdminOnly;
    }
    public short getQstMax() {
        return this.qstMax;
    }
    
    public void setQstMax(short qstMax) {
        this.qstMax = qstMax;
    }
    public Long getQstWpUser() {
        return this.qstWpUser;
    }
    
    public void setQstWpUser(Long qstWpUser) {
        this.qstWpUser = qstWpUser;
    }
    public byte getQstDeleted() {
        return this.qstDeleted;
    }
    
    public void setQstDeleted(byte qstDeleted) {
        this.qstDeleted = qstDeleted;
    }




}


