package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspAttendeeMeta generated by hbm2java
 */
public class WpEspAttendeeMeta  implements java.io.Serializable {


     private Integer attmId;
     private long attId;
     private String attFname;
     private String attLname;
     private String attAddress;
     private String attAddress2;
     private String attCity;
     private Integer staId;
     private String cntIso;
     private String attZip;
     private String attEmail;
     private String attPhone;

    public WpEspAttendeeMeta() {
    }

	
    public WpEspAttendeeMeta(long attId, String attFname, String attLname, String attEmail) {
        this.attId = attId;
        this.attFname = attFname;
        this.attLname = attLname;
        this.attEmail = attEmail;
    }
    public WpEspAttendeeMeta(long attId, String attFname, String attLname, String attAddress, String attAddress2, String attCity, Integer staId, String cntIso, String attZip, String attEmail, String attPhone) {
       this.attId = attId;
       this.attFname = attFname;
       this.attLname = attLname;
       this.attAddress = attAddress;
       this.attAddress2 = attAddress2;
       this.attCity = attCity;
       this.staId = staId;
       this.cntIso = cntIso;
       this.attZip = attZip;
       this.attEmail = attEmail;
       this.attPhone = attPhone;
    }
   
    public Integer getAttmId() {
        return this.attmId;
    }
    
    public void setAttmId(Integer attmId) {
        this.attmId = attmId;
    }
    public long getAttId() {
        return this.attId;
    }
    
    public void setAttId(long attId) {
        this.attId = attId;
    }
    public String getAttFname() {
        return this.attFname;
    }
    
    public void setAttFname(String attFname) {
        this.attFname = attFname;
    }
    public String getAttLname() {
        return this.attLname;
    }
    
    public void setAttLname(String attLname) {
        this.attLname = attLname;
    }
    public String getAttAddress() {
        return this.attAddress;
    }
    
    public void setAttAddress(String attAddress) {
        this.attAddress = attAddress;
    }
    public String getAttAddress2() {
        return this.attAddress2;
    }
    
    public void setAttAddress2(String attAddress2) {
        this.attAddress2 = attAddress2;
    }
    public String getAttCity() {
        return this.attCity;
    }
    
    public void setAttCity(String attCity) {
        this.attCity = attCity;
    }
    public Integer getStaId() {
        return this.staId;
    }
    
    public void setStaId(Integer staId) {
        this.staId = staId;
    }
    public String getCntIso() {
        return this.cntIso;
    }
    
    public void setCntIso(String cntIso) {
        this.cntIso = cntIso;
    }
    public String getAttZip() {
        return this.attZip;
    }
    
    public void setAttZip(String attZip) {
        this.attZip = attZip;
    }
    public String getAttEmail() {
        return this.attEmail;
    }
    
    public void setAttEmail(String attEmail) {
        this.attEmail = attEmail;
    }
    public String getAttPhone() {
        return this.attPhone;
    }
    
    public void setAttPhone(String attPhone) {
        this.attPhone = attPhone;
    }




}


