package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspDatetimeTicket generated by hbm2java
 */
public class WpEspDatetimeTicket  implements java.io.Serializable {


     private Integer dtkId;
     private int dttId;
     private int tktId;

    public WpEspDatetimeTicket() {
    }

    public WpEspDatetimeTicket(int dttId, int tktId) {
       this.dttId = dttId;
       this.tktId = tktId;
    }
   
    public Integer getDtkId() {
        return this.dtkId;
    }
    
    public void setDtkId(Integer dtkId) {
        this.dtkId = dtkId;
    }
    public int getDttId() {
        return this.dttId;
    }
    
    public void setDttId(int dttId) {
        this.dttId = dttId;
    }
    public int getTktId() {
        return this.tktId;
    }
    
    public void setTktId(int tktId) {
        this.tktId = tktId;
    }




}


