package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspQuestionGroupQuestion generated by hbm2java
 */
public class WpEspQuestionGroupQuestion  implements java.io.Serializable {


     private Integer qgqId;
     private int qsgId;
     private int qstId;
     private int qgqOrder;

    public WpEspQuestionGroupQuestion() {
    }

    public WpEspQuestionGroupQuestion(int qsgId, int qstId, int qgqOrder) {
       this.qsgId = qsgId;
       this.qstId = qstId;
       this.qgqOrder = qgqOrder;
    }
   
    public Integer getQgqId() {
        return this.qgqId;
    }
    
    public void setQgqId(Integer qgqId) {
        this.qgqId = qgqId;
    }
    public int getQsgId() {
        return this.qsgId;
    }
    
    public void setQsgId(int qsgId) {
        this.qsgId = qsgId;
    }
    public int getQstId() {
        return this.qstId;
    }
    
    public void setQstId(int qstId) {
        this.qstId = qstId;
    }
    public int getQgqOrder() {
        return this.qgqOrder;
    }
    
    public void setQgqOrder(int qgqOrder) {
        this.qgqOrder = qgqOrder;
    }




}


