package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WpEspDatetime generated by hbm2java
 */
public class WpEspDatetime  implements java.io.Serializable {


     private Integer dttId;
     private long evtId;
     private String dttName;
     private String dttDescription;
     private Date dttEvtStart;
     private Date dttEvtEnd;
     private Integer dttRegLimit;
     private Integer dttSold;
     private boolean dttIsPrimary;
     private Integer dttOrder;
     private Integer dttParent;
     private boolean dttDeleted;

    public WpEspDatetime() {
    }

	
    public WpEspDatetime(long evtId, String dttName, String dttDescription, Date dttEvtStart, Date dttEvtEnd, boolean dttIsPrimary, boolean dttDeleted) {
        this.evtId = evtId;
        this.dttName = dttName;
        this.dttDescription = dttDescription;
        this.dttEvtStart = dttEvtStart;
        this.dttEvtEnd = dttEvtEnd;
        this.dttIsPrimary = dttIsPrimary;
        this.dttDeleted = dttDeleted;
    }
    public WpEspDatetime(long evtId, String dttName, String dttDescription, Date dttEvtStart, Date dttEvtEnd, Integer dttRegLimit, Integer dttSold, boolean dttIsPrimary, Integer dttOrder, Integer dttParent, boolean dttDeleted) {
       this.evtId = evtId;
       this.dttName = dttName;
       this.dttDescription = dttDescription;
       this.dttEvtStart = dttEvtStart;
       this.dttEvtEnd = dttEvtEnd;
       this.dttRegLimit = dttRegLimit;
       this.dttSold = dttSold;
       this.dttIsPrimary = dttIsPrimary;
       this.dttOrder = dttOrder;
       this.dttParent = dttParent;
       this.dttDeleted = dttDeleted;
    }
   
    public Integer getDttId() {
        return this.dttId;
    }
    
    public void setDttId(Integer dttId) {
        this.dttId = dttId;
    }
    public long getEvtId() {
        return this.evtId;
    }
    
    public void setEvtId(long evtId) {
        this.evtId = evtId;
    }
    public String getDttName() {
        return this.dttName;
    }
    
    public void setDttName(String dttName) {
        this.dttName = dttName;
    }
    public String getDttDescription() {
        return this.dttDescription;
    }
    
    public void setDttDescription(String dttDescription) {
        this.dttDescription = dttDescription;
    }
    public Date getDttEvtStart() {
        return this.dttEvtStart;
    }
    
    public void setDttEvtStart(Date dttEvtStart) {
        this.dttEvtStart = dttEvtStart;
    }
    public Date getDttEvtEnd() {
        return this.dttEvtEnd;
    }
    
    public void setDttEvtEnd(Date dttEvtEnd) {
        this.dttEvtEnd = dttEvtEnd;
    }
    public Integer getDttRegLimit() {
        return this.dttRegLimit;
    }
    
    public void setDttRegLimit(Integer dttRegLimit) {
        this.dttRegLimit = dttRegLimit;
    }
    public Integer getDttSold() {
        return this.dttSold;
    }
    
    public void setDttSold(Integer dttSold) {
        this.dttSold = dttSold;
    }
    public boolean isDttIsPrimary() {
        return this.dttIsPrimary;
    }
    
    public void setDttIsPrimary(boolean dttIsPrimary) {
        this.dttIsPrimary = dttIsPrimary;
    }
    public Integer getDttOrder() {
        return this.dttOrder;
    }
    
    public void setDttOrder(Integer dttOrder) {
        this.dttOrder = dttOrder;
    }
    public Integer getDttParent() {
        return this.dttParent;
    }
    
    public void setDttParent(Integer dttParent) {
        this.dttParent = dttParent;
    }
    public boolean isDttDeleted() {
        return this.dttDeleted;
    }
    
    public void setDttDeleted(boolean dttDeleted) {
        this.dttDeleted = dttDeleted;
    }




}


