package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * WpEspPayment generated by hbm2java
 */
public class WpEspPayment  implements java.io.Serializable {


     private Integer payId;
     private Integer txnId;
     private String stsId;
     private Date payTimestamp;
     private String paySource;
     private BigDecimal payAmount;
     private Integer pmdId;
     private String payGatewayResponse;
     private String payTxnIdChqNmbr;
     private String payPoNumber;
     private String payExtraAccntng;
     private String payDetails;
     private String payRedirectUrl;
     private String payRedirectArgs;

    public WpEspPayment() {
    }

	
    public WpEspPayment(Date payTimestamp) {
        this.payTimestamp = payTimestamp;
    }
    public WpEspPayment(Integer txnId, String stsId, Date payTimestamp, String paySource, BigDecimal payAmount, Integer pmdId, String payGatewayResponse, String payTxnIdChqNmbr, String payPoNumber, String payExtraAccntng, String payDetails, String payRedirectUrl, String payRedirectArgs) {
       this.txnId = txnId;
       this.stsId = stsId;
       this.payTimestamp = payTimestamp;
       this.paySource = paySource;
       this.payAmount = payAmount;
       this.pmdId = pmdId;
       this.payGatewayResponse = payGatewayResponse;
       this.payTxnIdChqNmbr = payTxnIdChqNmbr;
       this.payPoNumber = payPoNumber;
       this.payExtraAccntng = payExtraAccntng;
       this.payDetails = payDetails;
       this.payRedirectUrl = payRedirectUrl;
       this.payRedirectArgs = payRedirectArgs;
    }
   
    public Integer getPayId() {
        return this.payId;
    }
    
    public void setPayId(Integer payId) {
        this.payId = payId;
    }
    public Integer getTxnId() {
        return this.txnId;
    }
    
    public void setTxnId(Integer txnId) {
        this.txnId = txnId;
    }
    public String getStsId() {
        return this.stsId;
    }
    
    public void setStsId(String stsId) {
        this.stsId = stsId;
    }
    public Date getPayTimestamp() {
        return this.payTimestamp;
    }
    
    public void setPayTimestamp(Date payTimestamp) {
        this.payTimestamp = payTimestamp;
    }
    public String getPaySource() {
        return this.paySource;
    }
    
    public void setPaySource(String paySource) {
        this.paySource = paySource;
    }
    public BigDecimal getPayAmount() {
        return this.payAmount;
    }
    
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }
    public Integer getPmdId() {
        return this.pmdId;
    }
    
    public void setPmdId(Integer pmdId) {
        this.pmdId = pmdId;
    }
    public String getPayGatewayResponse() {
        return this.payGatewayResponse;
    }
    
    public void setPayGatewayResponse(String payGatewayResponse) {
        this.payGatewayResponse = payGatewayResponse;
    }
    public String getPayTxnIdChqNmbr() {
        return this.payTxnIdChqNmbr;
    }
    
    public void setPayTxnIdChqNmbr(String payTxnIdChqNmbr) {
        this.payTxnIdChqNmbr = payTxnIdChqNmbr;
    }
    public String getPayPoNumber() {
        return this.payPoNumber;
    }
    
    public void setPayPoNumber(String payPoNumber) {
        this.payPoNumber = payPoNumber;
    }
    public String getPayExtraAccntng() {
        return this.payExtraAccntng;
    }
    
    public void setPayExtraAccntng(String payExtraAccntng) {
        this.payExtraAccntng = payExtraAccntng;
    }
    public String getPayDetails() {
        return this.payDetails;
    }
    
    public void setPayDetails(String payDetails) {
        this.payDetails = payDetails;
    }
    public String getPayRedirectUrl() {
        return this.payRedirectUrl;
    }
    
    public void setPayRedirectUrl(String payRedirectUrl) {
        this.payRedirectUrl = payRedirectUrl;
    }
    public String getPayRedirectArgs() {
        return this.payRedirectArgs;
    }
    
    public void setPayRedirectArgs(String payRedirectArgs) {
        this.payRedirectArgs = payRedirectArgs;
    }




}


