package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspExtraMeta generated by hbm2java
 */
public class WpEspExtraMeta  implements java.io.Serializable {


     private Integer exmId;
     private Integer objId;
     private String exmType;
     private String exmKey;
     private String exmValue;

    public WpEspExtraMeta() {
    }

    public WpEspExtraMeta(Integer objId, String exmType, String exmKey, String exmValue) {
       this.objId = objId;
       this.exmType = exmType;
       this.exmKey = exmKey;
       this.exmValue = exmValue;
    }
   
    public Integer getExmId() {
        return this.exmId;
    }
    
    public void setExmId(Integer exmId) {
        this.exmId = exmId;
    }
    public Integer getObjId() {
        return this.objId;
    }
    
    public void setObjId(Integer objId) {
        this.objId = objId;
    }
    public String getExmType() {
        return this.exmType;
    }
    
    public void setExmType(String exmType) {
        this.exmType = exmType;
    }
    public String getExmKey() {
        return this.exmKey;
    }
    
    public void setExmKey(String exmKey) {
        this.exmKey = exmKey;
    }
    public String getExmValue() {
        return this.exmValue;
    }
    
    public void setExmValue(String exmValue) {
        this.exmValue = exmValue;
    }




}


