package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspCurrencyPaymentMethod generated by hbm2java
 */
public class WpEspCurrencyPaymentMethod  implements java.io.Serializable {


     private Integer cpmId;
     private String curCode;
     private int pmdId;

    public WpEspCurrencyPaymentMethod() {
    }

    public WpEspCurrencyPaymentMethod(String curCode, int pmdId) {
       this.curCode = curCode;
       this.pmdId = pmdId;
    }
   
    public Integer getCpmId() {
        return this.cpmId;
    }
    
    public void setCpmId(Integer cpmId) {
        this.cpmId = cpmId;
    }
    public String getCurCode() {
        return this.curCode;
    }
    
    public void setCurCode(String curCode) {
        this.curCode = curCode;
    }
    public int getPmdId() {
        return this.pmdId;
    }
    
    public void setPmdId(int pmdId) {
        this.pmdId = pmdId;
    }




}


