package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WpEspEventMeta generated by hbm2java
 */
public class WpEspEventMeta  implements java.io.Serializable {


     private Integer evtmId;
     private long evtId;
     private boolean evtDisplayDesc;
     private boolean evtDisplayTicketSelector;
     private Date evtVisibleOn;
     private String evtDefaultRegistrationStatus;
     private String evtPhone;
     private Byte evtAdditionalLimit;
     private boolean evtMemberOnly;
     private boolean evtAllowOverflow;
     private String evtTimezoneString;
     private String evtExternalUrl;
     private Boolean evtDonations;

    public WpEspEventMeta() {
    }

	
    public WpEspEventMeta(long evtId, boolean evtDisplayDesc, boolean evtDisplayTicketSelector, Date evtVisibleOn, boolean evtMemberOnly, boolean evtAllowOverflow) {
        this.evtId = evtId;
        this.evtDisplayDesc = evtDisplayDesc;
        this.evtDisplayTicketSelector = evtDisplayTicketSelector;
        this.evtVisibleOn = evtVisibleOn;
        this.evtMemberOnly = evtMemberOnly;
        this.evtAllowOverflow = evtAllowOverflow;
    }
    public WpEspEventMeta(long evtId, boolean evtDisplayDesc, boolean evtDisplayTicketSelector, Date evtVisibleOn, String evtDefaultRegistrationStatus, String evtPhone, Byte evtAdditionalLimit, boolean evtMemberOnly, boolean evtAllowOverflow, String evtTimezoneString, String evtExternalUrl, Boolean evtDonations) {
       this.evtId = evtId;
       this.evtDisplayDesc = evtDisplayDesc;
       this.evtDisplayTicketSelector = evtDisplayTicketSelector;
       this.evtVisibleOn = evtVisibleOn;
       this.evtDefaultRegistrationStatus = evtDefaultRegistrationStatus;
       this.evtPhone = evtPhone;
       this.evtAdditionalLimit = evtAdditionalLimit;
       this.evtMemberOnly = evtMemberOnly;
       this.evtAllowOverflow = evtAllowOverflow;
       this.evtTimezoneString = evtTimezoneString;
       this.evtExternalUrl = evtExternalUrl;
       this.evtDonations = evtDonations;
    }
   
    public Integer getEvtmId() {
        return this.evtmId;
    }
    
    public void setEvtmId(Integer evtmId) {
        this.evtmId = evtmId;
    }
    public long getEvtId() {
        return this.evtId;
    }
    
    public void setEvtId(long evtId) {
        this.evtId = evtId;
    }
    public boolean isEvtDisplayDesc() {
        return this.evtDisplayDesc;
    }
    
    public void setEvtDisplayDesc(boolean evtDisplayDesc) {
        this.evtDisplayDesc = evtDisplayDesc;
    }
    public boolean isEvtDisplayTicketSelector() {
        return this.evtDisplayTicketSelector;
    }
    
    public void setEvtDisplayTicketSelector(boolean evtDisplayTicketSelector) {
        this.evtDisplayTicketSelector = evtDisplayTicketSelector;
    }
    public Date getEvtVisibleOn() {
        return this.evtVisibleOn;
    }
    
    public void setEvtVisibleOn(Date evtVisibleOn) {
        this.evtVisibleOn = evtVisibleOn;
    }
    public String getEvtDefaultRegistrationStatus() {
        return this.evtDefaultRegistrationStatus;
    }
    
    public void setEvtDefaultRegistrationStatus(String evtDefaultRegistrationStatus) {
        this.evtDefaultRegistrationStatus = evtDefaultRegistrationStatus;
    }
    public String getEvtPhone() {
        return this.evtPhone;
    }
    
    public void setEvtPhone(String evtPhone) {
        this.evtPhone = evtPhone;
    }
    public Byte getEvtAdditionalLimit() {
        return this.evtAdditionalLimit;
    }
    
    public void setEvtAdditionalLimit(Byte evtAdditionalLimit) {
        this.evtAdditionalLimit = evtAdditionalLimit;
    }
    public boolean isEvtMemberOnly() {
        return this.evtMemberOnly;
    }
    
    public void setEvtMemberOnly(boolean evtMemberOnly) {
        this.evtMemberOnly = evtMemberOnly;
    }
    public boolean isEvtAllowOverflow() {
        return this.evtAllowOverflow;
    }
    
    public void setEvtAllowOverflow(boolean evtAllowOverflow) {
        this.evtAllowOverflow = evtAllowOverflow;
    }
    public String getEvtTimezoneString() {
        return this.evtTimezoneString;
    }
    
    public void setEvtTimezoneString(String evtTimezoneString) {
        this.evtTimezoneString = evtTimezoneString;
    }
    public String getEvtExternalUrl() {
        return this.evtExternalUrl;
    }
    
    public void setEvtExternalUrl(String evtExternalUrl) {
        this.evtExternalUrl = evtExternalUrl;
    }
    public Boolean getEvtDonations() {
        return this.evtDonations;
    }
    
    public void setEvtDonations(Boolean evtDonations) {
        this.evtDonations = evtDonations;
    }




}


