package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspPriceType generated by hbm2java
 */
public class WpEspPriceType  implements java.io.Serializable {


     private Byte prtId;
     private String prtName;
     private byte pbtId;
     private boolean prtIsPercent;
     private Byte prtOrder;
     private Long prtWpUser;
     private boolean prtDeleted;

    public WpEspPriceType() {
    }

	
    public WpEspPriceType(String prtName, byte pbtId, boolean prtIsPercent, boolean prtDeleted) {
        this.prtName = prtName;
        this.pbtId = pbtId;
        this.prtIsPercent = prtIsPercent;
        this.prtDeleted = prtDeleted;
    }
    public WpEspPriceType(String prtName, byte pbtId, boolean prtIsPercent, Byte prtOrder, Long prtWpUser, boolean prtDeleted) {
       this.prtName = prtName;
       this.pbtId = pbtId;
       this.prtIsPercent = prtIsPercent;
       this.prtOrder = prtOrder;
       this.prtWpUser = prtWpUser;
       this.prtDeleted = prtDeleted;
    }
   
    public Byte getPrtId() {
        return this.prtId;
    }
    
    public void setPrtId(Byte prtId) {
        this.prtId = prtId;
    }
    public String getPrtName() {
        return this.prtName;
    }
    
    public void setPrtName(String prtName) {
        this.prtName = prtName;
    }
    public byte getPbtId() {
        return this.pbtId;
    }
    
    public void setPbtId(byte pbtId) {
        this.pbtId = pbtId;
    }
    public boolean isPrtIsPercent() {
        return this.prtIsPercent;
    }
    
    public void setPrtIsPercent(boolean prtIsPercent) {
        this.prtIsPercent = prtIsPercent;
    }
    public Byte getPrtOrder() {
        return this.prtOrder;
    }
    
    public void setPrtOrder(Byte prtOrder) {
        this.prtOrder = prtOrder;
    }
    public Long getPrtWpUser() {
        return this.prtWpUser;
    }
    
    public void setPrtWpUser(Long prtWpUser) {
        this.prtWpUser = prtWpUser;
    }
    public boolean isPrtDeleted() {
        return this.prtDeleted;
    }
    
    public void setPrtDeleted(boolean prtDeleted) {
        this.prtDeleted = prtDeleted;
    }




}


