package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspTicketTemplate generated by hbm2java
 */
public class WpEspTicketTemplate  implements java.io.Serializable {


     private Integer ttmId;
     private String ttmName;
     private String ttmDescription;
     private String ttmFile;

    public WpEspTicketTemplate() {
    }

	
    public WpEspTicketTemplate(String ttmName) {
        this.ttmName = ttmName;
    }
    public WpEspTicketTemplate(String ttmName, String ttmDescription, String ttmFile) {
       this.ttmName = ttmName;
       this.ttmDescription = ttmDescription;
       this.ttmFile = ttmFile;
    }
   
    public Integer getTtmId() {
        return this.ttmId;
    }
    
    public void setTtmId(Integer ttmId) {
        this.ttmId = ttmId;
    }
    public String getTtmName() {
        return this.ttmName;
    }
    
    public void setTtmName(String ttmName) {
        this.ttmName = ttmName;
    }
    public String getTtmDescription() {
        return this.ttmDescription;
    }
    
    public void setTtmDescription(String ttmDescription) {
        this.ttmDescription = ttmDescription;
    }
    public String getTtmFile() {
        return this.ttmFile;
    }
    
    public void setTtmFile(String ttmFile) {
        this.ttmFile = ttmFile;
    }




}


