package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspAnswer generated by hbm2java
 */
public class WpEspAnswer  implements java.io.Serializable {


     private Integer ansId;
     private int regId;
     private int qstId;
     private String ansValue;

    public WpEspAnswer() {
    }

    public WpEspAnswer(int regId, int qstId, String ansValue) {
       this.regId = regId;
       this.qstId = qstId;
       this.ansValue = ansValue;
    }
   
    public Integer getAnsId() {
        return this.ansId;
    }
    
    public void setAnsId(Integer ansId) {
        this.ansId = ansId;
    }
    public int getRegId() {
        return this.regId;
    }
    
    public void setRegId(int regId) {
        this.regId = regId;
    }
    public int getQstId() {
        return this.qstId;
    }
    
    public void setQstId(int qstId) {
        this.qstId = qstId;
    }
    public String getAnsValue() {
        return this.ansValue;
    }
    
    public void setAnsValue(String ansValue) {
        this.ansValue = ansValue;
    }




}


