package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspExtraJoin generated by hbm2java
 */
public class WpEspExtraJoin  implements java.io.Serializable {


     private Integer exjId;
     private String exjFirstModelId;
     private String exjFirstModelName;
     private String exjSecondModelId;
     private String exjSecondModelName;

    public WpEspExtraJoin() {
    }

    public WpEspExtraJoin(String exjFirstModelId, String exjFirstModelName, String exjSecondModelId, String exjSecondModelName) {
       this.exjFirstModelId = exjFirstModelId;
       this.exjFirstModelName = exjFirstModelName;
       this.exjSecondModelId = exjSecondModelId;
       this.exjSecondModelName = exjSecondModelName;
    }
   
    public Integer getExjId() {
        return this.exjId;
    }
    
    public void setExjId(Integer exjId) {
        this.exjId = exjId;
    }
    public String getExjFirstModelId() {
        return this.exjFirstModelId;
    }
    
    public void setExjFirstModelId(String exjFirstModelId) {
        this.exjFirstModelId = exjFirstModelId;
    }
    public String getExjFirstModelName() {
        return this.exjFirstModelName;
    }
    
    public void setExjFirstModelName(String exjFirstModelName) {
        this.exjFirstModelName = exjFirstModelName;
    }
    public String getExjSecondModelId() {
        return this.exjSecondModelId;
    }
    
    public void setExjSecondModelId(String exjSecondModelId) {
        this.exjSecondModelId = exjSecondModelId;
    }
    public String getExjSecondModelName() {
        return this.exjSecondModelName;
    }
    
    public void setExjSecondModelName(String exjSecondModelName) {
        this.exjSecondModelName = exjSecondModelName;
    }




}


