package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * WpEspRegistration generated by hbm2java
 */
public class WpEspRegistration  implements java.io.Serializable {


     private Integer regId;
     private long evtId;
     private long attId;
     private int txnId;
     private int tktId;
     private String stsId;
     private Date regDate;
     private BigDecimal regFinalPrice;
     private BigDecimal regPaid;
     private String regSession;
     private String regCode;
     private String regUrlLink;
     private Byte regCount;
     private Byte regGroupSize;
     private Boolean regAttIsGoing;
     private Boolean regDeleted;

    public WpEspRegistration() {
    }

	
    public WpEspRegistration(long evtId, long attId, int txnId, int tktId, String stsId, Date regDate, BigDecimal regFinalPrice, BigDecimal regPaid, String regSession) {
        this.evtId = evtId;
        this.attId = attId;
        this.txnId = txnId;
        this.tktId = tktId;
        this.stsId = stsId;
        this.regDate = regDate;
        this.regFinalPrice = regFinalPrice;
        this.regPaid = regPaid;
        this.regSession = regSession;
    }
    public WpEspRegistration(long evtId, long attId, int txnId, int tktId, String stsId, Date regDate, BigDecimal regFinalPrice, BigDecimal regPaid, String regSession, String regCode, String regUrlLink, Byte regCount, Byte regGroupSize, Boolean regAttIsGoing, Boolean regDeleted) {
       this.evtId = evtId;
       this.attId = attId;
       this.txnId = txnId;
       this.tktId = tktId;
       this.stsId = stsId;
       this.regDate = regDate;
       this.regFinalPrice = regFinalPrice;
       this.regPaid = regPaid;
       this.regSession = regSession;
       this.regCode = regCode;
       this.regUrlLink = regUrlLink;
       this.regCount = regCount;
       this.regGroupSize = regGroupSize;
       this.regAttIsGoing = regAttIsGoing;
       this.regDeleted = regDeleted;
    }
   
    public Integer getRegId() {
        return this.regId;
    }
    
    public void setRegId(Integer regId) {
        this.regId = regId;
    }
    public long getEvtId() {
        return this.evtId;
    }
    
    public void setEvtId(long evtId) {
        this.evtId = evtId;
    }
    public long getAttId() {
        return this.attId;
    }
    
    public void setAttId(long attId) {
        this.attId = attId;
    }
    public int getTxnId() {
        return this.txnId;
    }
    
    public void setTxnId(int txnId) {
        this.txnId = txnId;
    }
    public int getTktId() {
        return this.tktId;
    }
    
    public void setTktId(int tktId) {
        this.tktId = tktId;
    }
    public String getStsId() {
        return this.stsId;
    }
    
    public void setStsId(String stsId) {
        this.stsId = stsId;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public BigDecimal getRegFinalPrice() {
        return this.regFinalPrice;
    }
    
    public void setRegFinalPrice(BigDecimal regFinalPrice) {
        this.regFinalPrice = regFinalPrice;
    }
    public BigDecimal getRegPaid() {
        return this.regPaid;
    }
    
    public void setRegPaid(BigDecimal regPaid) {
        this.regPaid = regPaid;
    }
    public String getRegSession() {
        return this.regSession;
    }
    
    public void setRegSession(String regSession) {
        this.regSession = regSession;
    }
    public String getRegCode() {
        return this.regCode;
    }
    
    public void setRegCode(String regCode) {
        this.regCode = regCode;
    }
    public String getRegUrlLink() {
        return this.regUrlLink;
    }
    
    public void setRegUrlLink(String regUrlLink) {
        this.regUrlLink = regUrlLink;
    }
    public Byte getRegCount() {
        return this.regCount;
    }
    
    public void setRegCount(Byte regCount) {
        this.regCount = regCount;
    }
    public Byte getRegGroupSize() {
        return this.regGroupSize;
    }
    
    public void setRegGroupSize(Byte regGroupSize) {
        this.regGroupSize = regGroupSize;
    }
    public Boolean getRegAttIsGoing() {
        return this.regAttIsGoing;
    }
    
    public void setRegAttIsGoing(Boolean regAttIsGoing) {
        this.regAttIsGoing = regAttIsGoing;
    }
    public Boolean getRegDeleted() {
        return this.regDeleted;
    }
    
    public void setRegDeleted(Boolean regDeleted) {
        this.regDeleted = regDeleted;
    }




}


