package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * WpEspTransaction generated by hbm2java
 */
public class WpEspTransaction  implements java.io.Serializable {


     private Integer txnId;
     private Date txnTimestamp;
     private BigDecimal txnTotal;
     private BigDecimal txnPaid;
     private String stsId;
     private String txnSessionData;
     private String txnHashSalt;
     private Integer pmdId;
     private String txnRegSteps;

    public WpEspTransaction() {
    }

	
    public WpEspTransaction(Date txnTimestamp, BigDecimal txnPaid, String stsId) {
        this.txnTimestamp = txnTimestamp;
        this.txnPaid = txnPaid;
        this.stsId = stsId;
    }
    public WpEspTransaction(Date txnTimestamp, BigDecimal txnTotal, BigDecimal txnPaid, String stsId, String txnSessionData, String txnHashSalt, Integer pmdId, String txnRegSteps) {
       this.txnTimestamp = txnTimestamp;
       this.txnTotal = txnTotal;
       this.txnPaid = txnPaid;
       this.stsId = stsId;
       this.txnSessionData = txnSessionData;
       this.txnHashSalt = txnHashSalt;
       this.pmdId = pmdId;
       this.txnRegSteps = txnRegSteps;
    }
   
    public Integer getTxnId() {
        return this.txnId;
    }
    
    public void setTxnId(Integer txnId) {
        this.txnId = txnId;
    }
    public Date getTxnTimestamp() {
        return this.txnTimestamp;
    }
    
    public void setTxnTimestamp(Date txnTimestamp) {
        this.txnTimestamp = txnTimestamp;
    }
    public BigDecimal getTxnTotal() {
        return this.txnTotal;
    }
    
    public void setTxnTotal(BigDecimal txnTotal) {
        this.txnTotal = txnTotal;
    }
    public BigDecimal getTxnPaid() {
        return this.txnPaid;
    }
    
    public void setTxnPaid(BigDecimal txnPaid) {
        this.txnPaid = txnPaid;
    }
    public String getStsId() {
        return this.stsId;
    }
    
    public void setStsId(String stsId) {
        this.stsId = stsId;
    }
    public String getTxnSessionData() {
        return this.txnSessionData;
    }
    
    public void setTxnSessionData(String txnSessionData) {
        this.txnSessionData = txnSessionData;
    }
    public String getTxnHashSalt() {
        return this.txnHashSalt;
    }
    
    public void setTxnHashSalt(String txnHashSalt) {
        this.txnHashSalt = txnHashSalt;
    }
    public Integer getPmdId() {
        return this.pmdId;
    }
    
    public void setPmdId(Integer pmdId) {
        this.pmdId = pmdId;
    }
    public String getTxnRegSteps() {
        return this.txnRegSteps;
    }
    
    public void setTxnRegSteps(String txnRegSteps) {
        this.txnRegSteps = txnRegSteps;
    }




}


