package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspMessageTemplate generated by hbm2java
 */
public class WpEspMessageTemplate  implements java.io.Serializable {


     private Integer mtpId;
     private int grpId;
     private String mtpContext;
     private String mtpTemplateField;
     private String mtpContent;

    public WpEspMessageTemplate() {
    }

    public WpEspMessageTemplate(int grpId, String mtpContext, String mtpTemplateField, String mtpContent) {
       this.grpId = grpId;
       this.mtpContext = mtpContext;
       this.mtpTemplateField = mtpTemplateField;
       this.mtpContent = mtpContent;
    }
   
    public Integer getMtpId() {
        return this.mtpId;
    }
    
    public void setMtpId(Integer mtpId) {
        this.mtpId = mtpId;
    }
    public int getGrpId() {
        return this.grpId;
    }
    
    public void setGrpId(int grpId) {
        this.grpId = grpId;
    }
    public String getMtpContext() {
        return this.mtpContext;
    }
    
    public void setMtpContext(String mtpContext) {
        this.mtpContext = mtpContext;
    }
    public String getMtpTemplateField() {
        return this.mtpTemplateField;
    }
    
    public void setMtpTemplateField(String mtpTemplateField) {
        this.mtpTemplateField = mtpTemplateField;
    }
    public String getMtpContent() {
        return this.mtpContent;
    }
    
    public void setMtpContent(String mtpContent) {
        this.mtpContent = mtpContent;
    }




}


