package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * WpEspLineItem generated by hbm2java
 */
public class WpEspLineItem  implements java.io.Serializable {


     private Integer linId;
     private String linCode;
     private Integer txnId;
     private String linName;
     private String linDesc;
     private BigDecimal linUnitPrice;
     private BigDecimal linPercent;
     private Boolean linIsTaxable;
     private Integer linOrder;
     private Integer linParent;
     private String linType;
     private BigDecimal linTotal;
     private Integer linQuantity;
     private Integer objId;
     private String objType;
     private Date linTimestamp;

    public WpEspLineItem() {
    }

	
    public WpEspLineItem(String linCode, String linName, String linType, Date linTimestamp) {
        this.linCode = linCode;
        this.linName = linName;
        this.linType = linType;
        this.linTimestamp = linTimestamp;
    }
    public WpEspLineItem(String linCode, Integer txnId, String linName, String linDesc, BigDecimal linUnitPrice, BigDecimal linPercent, Boolean linIsTaxable, Integer linOrder, Integer linParent, String linType, BigDecimal linTotal, Integer linQuantity, Integer objId, String objType, Date linTimestamp) {
       this.linCode = linCode;
       this.txnId = txnId;
       this.linName = linName;
       this.linDesc = linDesc;
       this.linUnitPrice = linUnitPrice;
       this.linPercent = linPercent;
       this.linIsTaxable = linIsTaxable;
       this.linOrder = linOrder;
       this.linParent = linParent;
       this.linType = linType;
       this.linTotal = linTotal;
       this.linQuantity = linQuantity;
       this.objId = objId;
       this.objType = objType;
       this.linTimestamp = linTimestamp;
    }
   
    public Integer getLinId() {
        return this.linId;
    }
    
    public void setLinId(Integer linId) {
        this.linId = linId;
    }
    public String getLinCode() {
        return this.linCode;
    }
    
    public void setLinCode(String linCode) {
        this.linCode = linCode;
    }
    public Integer getTxnId() {
        return this.txnId;
    }
    
    public void setTxnId(Integer txnId) {
        this.txnId = txnId;
    }
    public String getLinName() {
        return this.linName;
    }
    
    public void setLinName(String linName) {
        this.linName = linName;
    }
    public String getLinDesc() {
        return this.linDesc;
    }
    
    public void setLinDesc(String linDesc) {
        this.linDesc = linDesc;
    }
    public BigDecimal getLinUnitPrice() {
        return this.linUnitPrice;
    }
    
    public void setLinUnitPrice(BigDecimal linUnitPrice) {
        this.linUnitPrice = linUnitPrice;
    }
    public BigDecimal getLinPercent() {
        return this.linPercent;
    }
    
    public void setLinPercent(BigDecimal linPercent) {
        this.linPercent = linPercent;
    }
    public Boolean getLinIsTaxable() {
        return this.linIsTaxable;
    }
    
    public void setLinIsTaxable(Boolean linIsTaxable) {
        this.linIsTaxable = linIsTaxable;
    }
    public Integer getLinOrder() {
        return this.linOrder;
    }
    
    public void setLinOrder(Integer linOrder) {
        this.linOrder = linOrder;
    }
    public Integer getLinParent() {
        return this.linParent;
    }
    
    public void setLinParent(Integer linParent) {
        this.linParent = linParent;
    }
    public String getLinType() {
        return this.linType;
    }
    
    public void setLinType(String linType) {
        this.linType = linType;
    }
    public BigDecimal getLinTotal() {
        return this.linTotal;
    }
    
    public void setLinTotal(BigDecimal linTotal) {
        this.linTotal = linTotal;
    }
    public Integer getLinQuantity() {
        return this.linQuantity;
    }
    
    public void setLinQuantity(Integer linQuantity) {
        this.linQuantity = linQuantity;
    }
    public Integer getObjId() {
        return this.objId;
    }
    
    public void setObjId(Integer objId) {
        this.objId = objId;
    }
    public String getObjType() {
        return this.objType;
    }
    
    public void setObjType(String objType) {
        this.objType = objType;
    }
    public Date getLinTimestamp() {
        return this.linTimestamp;
    }
    
    public void setLinTimestamp(Date linTimestamp) {
        this.linTimestamp = linTimestamp;
    }




}


