package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspQuestionOption generated by hbm2java
 */
public class WpEspQuestionOption  implements java.io.Serializable {


     private Integer qsoId;
     private String qsoValue;
     private String qsoDesc;
     private int qstId;
     private int qsoOrder;
     private String qsoSystem;
     private boolean qsoDeleted;

    public WpEspQuestionOption() {
    }

	
    public WpEspQuestionOption(String qsoValue, String qsoDesc, int qstId, int qsoOrder, boolean qsoDeleted) {
        this.qsoValue = qsoValue;
        this.qsoDesc = qsoDesc;
        this.qstId = qstId;
        this.qsoOrder = qsoOrder;
        this.qsoDeleted = qsoDeleted;
    }
    public WpEspQuestionOption(String qsoValue, String qsoDesc, int qstId, int qsoOrder, String qsoSystem, boolean qsoDeleted) {
       this.qsoValue = qsoValue;
       this.qsoDesc = qsoDesc;
       this.qstId = qstId;
       this.qsoOrder = qsoOrder;
       this.qsoSystem = qsoSystem;
       this.qsoDeleted = qsoDeleted;
    }
   
    public Integer getQsoId() {
        return this.qsoId;
    }
    
    public void setQsoId(Integer qsoId) {
        this.qsoId = qsoId;
    }
    public String getQsoValue() {
        return this.qsoValue;
    }
    
    public void setQsoValue(String qsoValue) {
        this.qsoValue = qsoValue;
    }
    public String getQsoDesc() {
        return this.qsoDesc;
    }
    
    public void setQsoDesc(String qsoDesc) {
        this.qsoDesc = qsoDesc;
    }
    public int getQstId() {
        return this.qstId;
    }
    
    public void setQstId(int qstId) {
        this.qstId = qstId;
    }
    public int getQsoOrder() {
        return this.qsoOrder;
    }
    
    public void setQsoOrder(int qsoOrder) {
        this.qsoOrder = qsoOrder;
    }
    public String getQsoSystem() {
        return this.qsoSystem;
    }
    
    public void setQsoSystem(String qsoSystem) {
        this.qsoSystem = qsoSystem;
    }
    public boolean isQsoDeleted() {
        return this.qsoDeleted;
    }
    
    public void setQsoDeleted(boolean qsoDeleted) {
        this.qsoDeleted = qsoDeleted;
    }




}


