package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspVenueMeta generated by hbm2java
 */
public class WpEspVenueMeta  implements java.io.Serializable {


     private Integer vnumId;
     private long vnuId;
     private String vnuAddress;
     private String vnuAddress2;
     private String vnuCity;
     private Integer staId;
     private String cntIso;
     private String vnuZip;
     private String vnuPhone;
     private Integer vnuCapacity;
     private String vnuUrl;
     private String vnuVirtualPhone;
     private String vnuVirtualUrl;
     private Boolean vnuEnableForGmap;
     private String vnuGoogleMapLink;

    public WpEspVenueMeta() {
    }

	
    public WpEspVenueMeta(long vnuId) {
        this.vnuId = vnuId;
    }
    public WpEspVenueMeta(long vnuId, String vnuAddress, String vnuAddress2, String vnuCity, Integer staId, String cntIso, String vnuZip, String vnuPhone, Integer vnuCapacity, String vnuUrl, String vnuVirtualPhone, String vnuVirtualUrl, Boolean vnuEnableForGmap, String vnuGoogleMapLink) {
       this.vnuId = vnuId;
       this.vnuAddress = vnuAddress;
       this.vnuAddress2 = vnuAddress2;
       this.vnuCity = vnuCity;
       this.staId = staId;
       this.cntIso = cntIso;
       this.vnuZip = vnuZip;
       this.vnuPhone = vnuPhone;
       this.vnuCapacity = vnuCapacity;
       this.vnuUrl = vnuUrl;
       this.vnuVirtualPhone = vnuVirtualPhone;
       this.vnuVirtualUrl = vnuVirtualUrl;
       this.vnuEnableForGmap = vnuEnableForGmap;
       this.vnuGoogleMapLink = vnuGoogleMapLink;
    }
   
    public Integer getVnumId() {
        return this.vnumId;
    }
    
    public void setVnumId(Integer vnumId) {
        this.vnumId = vnumId;
    }
    public long getVnuId() {
        return this.vnuId;
    }
    
    public void setVnuId(long vnuId) {
        this.vnuId = vnuId;
    }
    public String getVnuAddress() {
        return this.vnuAddress;
    }
    
    public void setVnuAddress(String vnuAddress) {
        this.vnuAddress = vnuAddress;
    }
    public String getVnuAddress2() {
        return this.vnuAddress2;
    }
    
    public void setVnuAddress2(String vnuAddress2) {
        this.vnuAddress2 = vnuAddress2;
    }
    public String getVnuCity() {
        return this.vnuCity;
    }
    
    public void setVnuCity(String vnuCity) {
        this.vnuCity = vnuCity;
    }
    public Integer getStaId() {
        return this.staId;
    }
    
    public void setStaId(Integer staId) {
        this.staId = staId;
    }
    public String getCntIso() {
        return this.cntIso;
    }
    
    public void setCntIso(String cntIso) {
        this.cntIso = cntIso;
    }
    public String getVnuZip() {
        return this.vnuZip;
    }
    
    public void setVnuZip(String vnuZip) {
        this.vnuZip = vnuZip;
    }
    public String getVnuPhone() {
        return this.vnuPhone;
    }
    
    public void setVnuPhone(String vnuPhone) {
        this.vnuPhone = vnuPhone;
    }
    public Integer getVnuCapacity() {
        return this.vnuCapacity;
    }
    
    public void setVnuCapacity(Integer vnuCapacity) {
        this.vnuCapacity = vnuCapacity;
    }
    public String getVnuUrl() {
        return this.vnuUrl;
    }
    
    public void setVnuUrl(String vnuUrl) {
        this.vnuUrl = vnuUrl;
    }
    public String getVnuVirtualPhone() {
        return this.vnuVirtualPhone;
    }
    
    public void setVnuVirtualPhone(String vnuVirtualPhone) {
        this.vnuVirtualPhone = vnuVirtualPhone;
    }
    public String getVnuVirtualUrl() {
        return this.vnuVirtualUrl;
    }
    
    public void setVnuVirtualUrl(String vnuVirtualUrl) {
        this.vnuVirtualUrl = vnuVirtualUrl;
    }
    public Boolean getVnuEnableForGmap() {
        return this.vnuEnableForGmap;
    }
    
    public void setVnuEnableForGmap(Boolean vnuEnableForGmap) {
        this.vnuEnableForGmap = vnuEnableForGmap;
    }
    public String getVnuGoogleMapLink() {
        return this.vnuGoogleMapLink;
    }
    
    public void setVnuGoogleMapLink(String vnuGoogleMapLink) {
        this.vnuGoogleMapLink = vnuGoogleMapLink;
    }




}


