package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspState generated by hbm2java
 */
public class WpEspState  implements java.io.Serializable {


     private Short staId;
     private String cntIso;
     private String staAbbrev;
     private String staName;
     private Boolean staActive;

    public WpEspState() {
    }

	
    public WpEspState(String cntIso, String staAbbrev, String staName) {
        this.cntIso = cntIso;
        this.staAbbrev = staAbbrev;
        this.staName = staName;
    }
    public WpEspState(String cntIso, String staAbbrev, String staName, Boolean staActive) {
       this.cntIso = cntIso;
       this.staAbbrev = staAbbrev;
       this.staName = staName;
       this.staActive = staActive;
    }
   
    public Short getStaId() {
        return this.staId;
    }
    
    public void setStaId(Short staId) {
        this.staId = staId;
    }
    public String getCntIso() {
        return this.cntIso;
    }
    
    public void setCntIso(String cntIso) {
        this.cntIso = cntIso;
    }
    public String getStaAbbrev() {
        return this.staAbbrev;
    }
    
    public void setStaAbbrev(String staAbbrev) {
        this.staAbbrev = staAbbrev;
    }
    public String getStaName() {
        return this.staName;
    }
    
    public void setStaName(String staName) {
        this.staName = staName;
    }
    public Boolean getStaActive() {
        return this.staActive;
    }
    
    public void setStaActive(Boolean staActive) {
        this.staActive = staActive;
    }




}


