package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpEspMessageTemplateGroup generated by hbm2java
 */
public class WpEspMessageTemplateGroup  implements java.io.Serializable {


     private Integer grpId;
     private int mtpUserId;
     private String mtpName;
     private String mtpDescription;
     private String mtpMessenger;
     private String mtpMessageType;
     private boolean mtpIsGlobal;
     private boolean mtpIsOverride;
     private boolean mtpDeleted;
     private boolean mtpIsActive;

    public WpEspMessageTemplateGroup() {
    }

    public WpEspMessageTemplateGroup(int mtpUserId, String mtpName, String mtpDescription, String mtpMessenger, String mtpMessageType, boolean mtpIsGlobal, boolean mtpIsOverride, boolean mtpDeleted, boolean mtpIsActive) {
       this.mtpUserId = mtpUserId;
       this.mtpName = mtpName;
       this.mtpDescription = mtpDescription;
       this.mtpMessenger = mtpMessenger;
       this.mtpMessageType = mtpMessageType;
       this.mtpIsGlobal = mtpIsGlobal;
       this.mtpIsOverride = mtpIsOverride;
       this.mtpDeleted = mtpDeleted;
       this.mtpIsActive = mtpIsActive;
    }
   
    public Integer getGrpId() {
        return this.grpId;
    }
    
    public void setGrpId(Integer grpId) {
        this.grpId = grpId;
    }
    public int getMtpUserId() {
        return this.mtpUserId;
    }
    
    public void setMtpUserId(int mtpUserId) {
        this.mtpUserId = mtpUserId;
    }
    public String getMtpName() {
        return this.mtpName;
    }
    
    public void setMtpName(String mtpName) {
        this.mtpName = mtpName;
    }
    public String getMtpDescription() {
        return this.mtpDescription;
    }
    
    public void setMtpDescription(String mtpDescription) {
        this.mtpDescription = mtpDescription;
    }
    public String getMtpMessenger() {
        return this.mtpMessenger;
    }
    
    public void setMtpMessenger(String mtpMessenger) {
        this.mtpMessenger = mtpMessenger;
    }
    public String getMtpMessageType() {
        return this.mtpMessageType;
    }
    
    public void setMtpMessageType(String mtpMessageType) {
        this.mtpMessageType = mtpMessageType;
    }
    public boolean isMtpIsGlobal() {
        return this.mtpIsGlobal;
    }
    
    public void setMtpIsGlobal(boolean mtpIsGlobal) {
        this.mtpIsGlobal = mtpIsGlobal;
    }
    public boolean isMtpIsOverride() {
        return this.mtpIsOverride;
    }
    
    public void setMtpIsOverride(boolean mtpIsOverride) {
        this.mtpIsOverride = mtpIsOverride;
    }
    public boolean isMtpDeleted() {
        return this.mtpDeleted;
    }
    
    public void setMtpDeleted(boolean mtpDeleted) {
        this.mtpDeleted = mtpDeleted;
    }
    public boolean isMtpIsActive() {
        return this.mtpIsActive;
    }
    
    public void setMtpIsActive(boolean mtpIsActive) {
        this.mtpIsActive = mtpIsActive;
    }




}


