package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * WpEspPrice generated by hbm2java
 */
public class WpEspPrice  implements java.io.Serializable {


     private Integer prcId;
     private byte prtId;
     private BigDecimal prcAmount;
     private String prcName;
     private String prcDesc;
     private boolean prcIsDefault;
     private Integer prcOverrides;
     private boolean prcDeleted;
     private byte prcOrder;
     private Long prcWpUser;
     private Integer prcParent;

    public WpEspPrice() {
    }

	
    public WpEspPrice(byte prtId, BigDecimal prcAmount, String prcName, boolean prcIsDefault, boolean prcDeleted, byte prcOrder) {
        this.prtId = prtId;
        this.prcAmount = prcAmount;
        this.prcName = prcName;
        this.prcIsDefault = prcIsDefault;
        this.prcDeleted = prcDeleted;
        this.prcOrder = prcOrder;
    }
    public WpEspPrice(byte prtId, BigDecimal prcAmount, String prcName, String prcDesc, boolean prcIsDefault, Integer prcOverrides, boolean prcDeleted, byte prcOrder, Long prcWpUser, Integer prcParent) {
       this.prtId = prtId;
       this.prcAmount = prcAmount;
       this.prcName = prcName;
       this.prcDesc = prcDesc;
       this.prcIsDefault = prcIsDefault;
       this.prcOverrides = prcOverrides;
       this.prcDeleted = prcDeleted;
       this.prcOrder = prcOrder;
       this.prcWpUser = prcWpUser;
       this.prcParent = prcParent;
    }
   
    public Integer getPrcId() {
        return this.prcId;
    }
    
    public void setPrcId(Integer prcId) {
        this.prcId = prcId;
    }
    public byte getPrtId() {
        return this.prtId;
    }
    
    public void setPrtId(byte prtId) {
        this.prtId = prtId;
    }
    public BigDecimal getPrcAmount() {
        return this.prcAmount;
    }
    
    public void setPrcAmount(BigDecimal prcAmount) {
        this.prcAmount = prcAmount;
    }
    public String getPrcName() {
        return this.prcName;
    }
    
    public void setPrcName(String prcName) {
        this.prcName = prcName;
    }
    public String getPrcDesc() {
        return this.prcDesc;
    }
    
    public void setPrcDesc(String prcDesc) {
        this.prcDesc = prcDesc;
    }
    public boolean isPrcIsDefault() {
        return this.prcIsDefault;
    }
    
    public void setPrcIsDefault(boolean prcIsDefault) {
        this.prcIsDefault = prcIsDefault;
    }
    public Integer getPrcOverrides() {
        return this.prcOverrides;
    }
    
    public void setPrcOverrides(Integer prcOverrides) {
        this.prcOverrides = prcOverrides;
    }
    public boolean isPrcDeleted() {
        return this.prcDeleted;
    }
    
    public void setPrcDeleted(boolean prcDeleted) {
        this.prcDeleted = prcDeleted;
    }
    public byte getPrcOrder() {
        return this.prcOrder;
    }
    
    public void setPrcOrder(byte prcOrder) {
        this.prcOrder = prcOrder;
    }
    public Long getPrcWpUser() {
        return this.prcWpUser;
    }
    
    public void setPrcWpUser(Long prcWpUser) {
        this.prcWpUser = prcWpUser;
    }
    public Integer getPrcParent() {
        return this.prcParent;
    }
    
    public void setPrcParent(Integer prcParent) {
        this.prcParent = prcParent;
    }




}


