package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpOptions generated by hbm2java
 */
public class WpOptions  implements java.io.Serializable {


     private Long optionId;
     private String optionName;
     private String optionValue;
     private String autoload;

    public WpOptions() {
    }

	
    public WpOptions(String optionValue, String autoload) {
        this.optionValue = optionValue;
        this.autoload = autoload;
    }
    public WpOptions(String optionName, String optionValue, String autoload) {
       this.optionName = optionName;
       this.optionValue = optionValue;
       this.autoload = autoload;
    }
   
    public Long getOptionId() {
        return this.optionId;
    }
    
    public void setOptionId(Long optionId) {
        this.optionId = optionId;
    }
    public String getOptionName() {
        return this.optionName;
    }
    
    public void setOptionName(String optionName) {
        this.optionName = optionName;
    }
    public String getOptionValue() {
        return this.optionValue;
    }
    
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue;
    }
    public String getAutoload() {
        return this.autoload;
    }
    
    public void setAutoload(String autoload) {
        this.autoload = autoload;
    }




}


