package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WpPosts generated by hbm2java
 */
public class WpPosts  implements java.io.Serializable {


     private Long id;
     private long postAuthor;
     private Date postDate;
     private Date postDateGmt;
     private String postContent;
     private String postTitle;
     private String postExcerpt;
     private String postStatus;
     private String commentStatus;
     private String pingStatus;
     private String postPassword;
     private String postName;
     private String toPing;
     private String pinged;
     private Date postModified;
     private Date postModifiedGmt;
     private String postContentFiltered;
     private long postParent;
     private String guid;
     private int menuOrder;
     private String postType;
     private String postMimeType;
     private long commentCount;

    public WpPosts() {
    }

    public WpPosts(long postAuthor, Date postDate, Date postDateGmt, String postContent, String postTitle, String postExcerpt, String postStatus, String commentStatus, String pingStatus, String postPassword, String postName, String toPing, String pinged, Date postModified, Date postModifiedGmt, String postContentFiltered, long postParent, String guid, int menuOrder, String postType, String postMimeType, long commentCount) {
       this.postAuthor = postAuthor;
       this.postDate = postDate;
       this.postDateGmt = postDateGmt;
       this.postContent = postContent;
       this.postTitle = postTitle;
       this.postExcerpt = postExcerpt;
       this.postStatus = postStatus;
       this.commentStatus = commentStatus;
       this.pingStatus = pingStatus;
       this.postPassword = postPassword;
       this.postName = postName;
       this.toPing = toPing;
       this.pinged = pinged;
       this.postModified = postModified;
       this.postModifiedGmt = postModifiedGmt;
       this.postContentFiltered = postContentFiltered;
       this.postParent = postParent;
       this.guid = guid;
       this.menuOrder = menuOrder;
       this.postType = postType;
       this.postMimeType = postMimeType;
       this.commentCount = commentCount;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getPostAuthor() {
        return this.postAuthor;
    }
    
    public void setPostAuthor(long postAuthor) {
        this.postAuthor = postAuthor;
    }
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }
    public Date getPostDateGmt() {
        return this.postDateGmt;
    }
    
    public void setPostDateGmt(Date postDateGmt) {
        this.postDateGmt = postDateGmt;
    }
    public String getPostContent() {
        return this.postContent;
    }
    
    public void setPostContent(String postContent) {
        this.postContent = postContent;
    }
    public String getPostTitle() {
        return this.postTitle;
    }
    
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }
    public String getPostExcerpt() {
        return this.postExcerpt;
    }
    
    public void setPostExcerpt(String postExcerpt) {
        this.postExcerpt = postExcerpt;
    }
    public String getPostStatus() {
        return this.postStatus;
    }
    
    public void setPostStatus(String postStatus) {
        this.postStatus = postStatus;
    }
    public String getCommentStatus() {
        return this.commentStatus;
    }
    
    public void setCommentStatus(String commentStatus) {
        this.commentStatus = commentStatus;
    }
    public String getPingStatus() {
        return this.pingStatus;
    }
    
    public void setPingStatus(String pingStatus) {
        this.pingStatus = pingStatus;
    }
    public String getPostPassword() {
        return this.postPassword;
    }
    
    public void setPostPassword(String postPassword) {
        this.postPassword = postPassword;
    }
    public String getPostName() {
        return this.postName;
    }
    
    public void setPostName(String postName) {
        this.postName = postName;
    }
    public String getToPing() {
        return this.toPing;
    }
    
    public void setToPing(String toPing) {
        this.toPing = toPing;
    }
    public String getPinged() {
        return this.pinged;
    }
    
    public void setPinged(String pinged) {
        this.pinged = pinged;
    }
    public Date getPostModified() {
        return this.postModified;
    }
    
    public void setPostModified(Date postModified) {
        this.postModified = postModified;
    }
    public Date getPostModifiedGmt() {
        return this.postModifiedGmt;
    }
    
    public void setPostModifiedGmt(Date postModifiedGmt) {
        this.postModifiedGmt = postModifiedGmt;
    }
    public String getPostContentFiltered() {
        return this.postContentFiltered;
    }
    
    public void setPostContentFiltered(String postContentFiltered) {
        this.postContentFiltered = postContentFiltered;
    }
    public long getPostParent() {
        return this.postParent;
    }
    
    public void setPostParent(long postParent) {
        this.postParent = postParent;
    }
    public String getGuid() {
        return this.guid;
    }
    
    public void setGuid(String guid) {
        this.guid = guid;
    }
    public int getMenuOrder() {
        return this.menuOrder;
    }
    
    public void setMenuOrder(int menuOrder) {
        this.menuOrder = menuOrder;
    }
    public String getPostType() {
        return this.postType;
    }
    
    public void setPostType(String postType) {
        this.postType = postType;
    }
    public String getPostMimeType() {
        return this.postMimeType;
    }
    
    public void setPostMimeType(String postMimeType) {
        this.postMimeType = postMimeType;
    }
    public long getCommentCount() {
        return this.commentCount;
    }
    
    public void setCommentCount(long commentCount) {
        this.commentCount = commentCount;
    }




}


