package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WpSignups generated by hbm2java
 */
public class WpSignups  implements java.io.Serializable {


     private Long signupId;
     private String domain;
     private String path;
     private String title;
     private String userLogin;
     private String userEmail;
     private Date registered;
     private Date activated;
     private boolean active;
     private String activationKey;
     private String meta;

    public WpSignups() {
    }

	
    public WpSignups(String domain, String path, String title, String userLogin, String userEmail, Date registered, Date activated, boolean active, String activationKey) {
        this.domain = domain;
        this.path = path;
        this.title = title;
        this.userLogin = userLogin;
        this.userEmail = userEmail;
        this.registered = registered;
        this.activated = activated;
        this.active = active;
        this.activationKey = activationKey;
    }
    public WpSignups(String domain, String path, String title, String userLogin, String userEmail, Date registered, Date activated, boolean active, String activationKey, String meta) {
       this.domain = domain;
       this.path = path;
       this.title = title;
       this.userLogin = userLogin;
       this.userEmail = userEmail;
       this.registered = registered;
       this.activated = activated;
       this.active = active;
       this.activationKey = activationKey;
       this.meta = meta;
    }
   
    public Long getSignupId() {
        return this.signupId;
    }
    
    public void setSignupId(Long signupId) {
        this.signupId = signupId;
    }
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public Date getRegistered() {
        return this.registered;
    }
    
    public void setRegistered(Date registered) {
        this.registered = registered;
    }
    public Date getActivated() {
        return this.activated;
    }
    
    public void setActivated(Date activated) {
        this.activated = activated;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public String getActivationKey() {
        return this.activationKey;
    }
    
    public void setActivationKey(String activationKey) {
        this.activationKey = activationKey;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }




}


