package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpTerms generated by hbm2java
 */
public class WpTerms  implements java.io.Serializable {


     private Long termId;
     private String name;
     private String slug;
     private long termGroup;

    public WpTerms() {
    }

    public WpTerms(String name, String slug, long termGroup) {
       this.name = name;
       this.slug = slug;
       this.termGroup = termGroup;
    }
   
    public Long getTermId() {
        return this.termId;
    }
    
    public void setTermId(Long termId) {
        this.termId = termId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSlug() {
        return this.slug;
    }
    
    public void setSlug(String slug) {
        this.slug = slug;
    }
    public long getTermGroup() {
        return this.termGroup;
    }
    
    public void setTermGroup(long termGroup) {
        this.termGroup = termGroup;
    }




}


