package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpTermRelationshipsId generated by hbm2java
 */
public class WpTermRelationshipsId  implements java.io.Serializable {


     private long objectId;
     private long termTaxonomyId;

    public WpTermRelationshipsId() {
    }

    public WpTermRelationshipsId(long objectId, long termTaxonomyId) {
       this.objectId = objectId;
       this.termTaxonomyId = termTaxonomyId;
    }
   
    public long getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(long objectId) {
        this.objectId = objectId;
    }
    public long getTermTaxonomyId() {
        return this.termTaxonomyId;
    }
    
    public void setTermTaxonomyId(long termTaxonomyId) {
        this.termTaxonomyId = termTaxonomyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WpTermRelationshipsId) ) return false;
		 WpTermRelationshipsId castOther = ( WpTermRelationshipsId ) other; 
         
		 return (this.getObjectId()==castOther.getObjectId())
 && (this.getTermTaxonomyId()==castOther.getTermTaxonomyId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getObjectId();
         result = 37 * result + (int) this.getTermTaxonomyId();
         return result;
   }   


}


