package edu.bullyingmestrado.dao;
// Generated 01/09/2016 05:04:57 PM by Hibernate Tools 4.3.1



/**
 * WpUsermeta generated by hbm2java
 */
public class WpUsermeta  implements java.io.Serializable {


     private Long umetaId;
     private long userId;
     private String metaKey;
     private String metaValue;

    public WpUsermeta() {
    }

	
    public WpUsermeta(long userId) {
        this.userId = userId;
    }
    public WpUsermeta(long userId, String metaKey, String metaValue) {
       this.userId = userId;
       this.metaKey = metaKey;
       this.metaValue = metaValue;
    }
   
    public Long getUmetaId() {
        return this.umetaId;
    }
    
    public void setUmetaId(Long umetaId) {
        this.umetaId = umetaId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getMetaKey() {
        return this.metaKey;
    }
    
    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey;
    }
    public String getMetaValue() {
        return this.metaValue;
    }
    
    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue;
    }




}


